name: shell commands

on: [push]


jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: echo string
        run: echo "hello Engineer"
      - name: Multiline script
        run: |
          node -v
          pwd
